---
- name: Converge
  hosts: all
  tasks:
    - name: "Molecule - include vars."
      ansible.builtin.include_vars: ./variables.yml
    - name: "Molecule - include role."
      ansible.builtin.include_role:
        name: "spreadcat.newsboat"
