---
newsboat_owner: sc
newsboat_group: sc
newsboat_home: /home/sc
newsboat_directories:
  - path: /home/sc/.newsboat
    state: directory
    mode: '0700'
newsboat_install_type: url
newsboat_download_url: 'https://github.com/newsboat/newsboat/archive/refs/tags/r2.30.1.tar.gz'
