---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include variables."
      ansible.builtin.include_vars: variables.yml

    - name: "Check for newsboat installation."
      ansible.builtin.shell: command -v newsboat
      register: _command_newsboat
      changed_when: false

    - name: "Assert newsboat is installed."
      ansible.builtin.assert:
        that: _command_newsboat.rc == 0
        quiet: true

    - name: "CHeck the directories exist."
      ansible.builtin.stat:
        path: "{{ item.path }}"
      loop: "{{ newsboat_directories }}"
      register: _stat_newsboat_directories

    - name: "Assert the user newsboat directory exist."
      ansible.builtin.assert:
        that:
          - item.stat.exists
        quiet: true
      loop: "{{ _stat_newsboat_directories.results }}"

    - name: "Check the configuration file exists."
      ansible.builtin.stat:
        path: "{{ newsboat_home }}/.newsboat/config"
      register: _newsboat_config

    - name: "Assert the configuration file exists."
      ansible.builtin.assert:
        that:
          - _newsboat_config.stat.exists
          - _newsboat_config.stat.mode == '0700'
        quiet: true

    - name: "Check the URL file exists."
      ansible.builtin.stat:
        path: "{{ newsboat_home }}/.newsboat/urls"
      register: _newsboat_urls

    - name: "Assert the URL file exists."
      ansible.builtin.assert:
        quiet: true
        that:
          - _newsboat_urls.stat.exists
          - _newsboat_urls.stat.mode == '0700'
