---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: INCLUDE VARIABLES
    include_vars: variables.yml
  - name: CHECK FOR NEWSBOAT INSTALLATION
    shell: command -v newsboat
    register: _command_newsboat
    changed_when: false
  - name: ASSERT NEWSBOAT IS INSTALLED
    ansible.builtin.assert:
      that: _command_newsboat.rc == 0
      quiet: true

  - name: CHECK THE DIRECTORIES EXIST
    ansible.builtin.stat:
      path: "{{ item.path }}"
    loop: "{{ newsboat_directories }}"
    register: _stat_newsboat_directories

  - name: ASSERT THE NEWSBOAT DIRECTORIES EXIST
    ansible.builtin.assert:
      that: 
        - item.stat.exists
      quiet: true
    loop: "{{ _stat_newsboat_directories.results }}"

  - name: CHECK THE CONFIG FILE EXISTS
    ansible.builtin.stat:
      path: "{{ newsboat_home }}/.newsboat/config"
    register: _newsboat_config

  - name: ASSERT CONFIG FILE EXIST
    ansible.builtin.assert:
      that:
        - _newsboat_config.stat.exists
        - _newsboat_config.stat.mode == '0700'
      quiet: true

  - name: CHECK URL FILE EXISTS
    ansible.builtin.stat:
      path: "{{ newsboat_home }}/.newsboat/urls"
    register: _newsboat_urls

  - name: ASSERT THE URLS FILE EXISTS
    ansible.builtin.assert:
      quiet: true
      that:
        - _newsboat_urls.stat.exists
        - _newsboat_urls.stat.mode == '0700'
