---
# Config file for newsboat
- name: "Config | Manage configuration file."
  ansible.builtin.template:
    src: config.j2
    dest: "{{ newsboat_home }}/.newsboat/config"
    owner: "{{ newsboat_owner }}"
    group: "{{ newsboat_group }}"
    mode: '0700'
    force: true

- name: "Config | Manage URLs."
  ansible.builtin.template:
    src: urls.j2
    dest: "{{ newsboat_home }}/.newsboat/urls"
    owner: "{{ newsboat_owner }}"
    group: "{{ newsboat_group }}"
    mode: '0700'
...
