---
# Newsboat installation via RPM package to download
- name: "Install URL | Manage and install tar.tz package."
  ansible.builtin.unarchive:
    src: "{{ newsboat_download_url }}"
    dest: /tmp
    remote_src: true
    creates: "/tmp/{{ newsboat_download_url | basename }}"

- name: "Install URL | Update APT cache."
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family|lower == 'debian'
  changed_when: false

- name: "Install URL | Store unarchive location."
  ansible.builtin.set_fact:
    # yamllint disable rule:line-length
    newsboat_unarchive_destination: >-
      "/tmp/newsboat-{{ newsboat_download_url | basename | replace('.tar.gz', '') }}"
    # yamllint enable rule:line-length

- name: "Install URL | Install build rewquirements."
  ansible.builtin.package:
    name: "{{ item }}"
  loop: "{{ newsboat_build[ansible_os_family | lower] }}"

- name: "Install URL | Install newsboat when missing."
  when: _command_newsboat.failed
  block:
    - name: "Install URL | Compile source-code."
      community.general.make:
        chdir: "{{ newsboat_unarchive_destination }}"

    - name: "Install URL | Install source-code."
      become: true
      community.general.make:
        target: install
        chdir: "{{ newsboat_unarchive_destination }}"
