---
- name: "Install | Manage directories."
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "{{ item.state | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ newsboat_directories | default({}) }}"

- name: "Install | Include install_package tasks."
  ansible.builtin.include_tasks: install_package.yml
  when: newsboat_install_type == 'package'

- name: "Install | Include install_url tasks."
  ansible.builtin.include_tasks: install_url.yml
  when: newsboat_install_type == 'url'
