---
- name: MANAGE DIRECTORIES
  file:
    path: "{{ item.path }}"
    state: "{{ item.state | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ newsboat_directories | default({}) }}"

- include_tasks: install_package.yml
  when: newsboat_install_type == 'package'
- include_tasks: install_url.yml
  when: newsboat_install_type == 'url'
