---
- name: "Install package | Update APT cache."
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family|lower == 'debian'
  changed_when: false

- name: "Install package | Manage package installation."
  become: true
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ newsboat_packages | default([]) }}"
...
