---
- name: "Main | URL requirement."
  when: newsboat_install_type == 'url'
  ansible.builtin.assert:
    quiet: true
    that:
      - newsboat_download_url|length > 0
    fail_msg: >
      Please define newsboat_rpm_download_url when setting
      newsboat_install_type to "url".'

# This requires the "shell" module. the command module fails on ubuntu 1804/2004
- name: "Main | Check for existing newsboat installation."
  ansible.builtin.shell: 'command -v newsboat'  # noqa command-instead-of-shell
  register: _command_newsboat
  changed_when: false
  failed_when: _command_newsboat.rc != 0
  ignore_errors: true

- name: "Main | Fetch newsboat version."
  when: not _command_newsboat.failed
  block:
    - name: "Main | Get newsboat version."
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          newsboat --version | grep Newsboat | head -n 1 | cut -d ' ' -f 2
      args:
        executable: /bin/bash
      register: _shell_newsboat_version
      changed_when: false

    - name: "Main | Register installed newsboat version."
      ansible.builtin.set_fact:
        newsboat_installed_version: "{{ _shell_newsboat_version.stdout }}"

- name: "Main | Include install tasks."
  ansible.builtin.include_tasks: install.yml

- name: "Main | Include config tasks."
  ansible.builtin.include_tasks: config.yml
