---
- name: Converge
  hosts: all
  tasks:
    - name: "Molecule default | Include vars."
      ansible.builtin.include_vars: ./variables.yml

    - name: "Molecule default | Include role."
      ansible.builtin.include_role:
        name: spreadcat.newsboat
