---
- name: Converge
  hosts: all
  tasks:
    - name: "Converge | Include varables."
      ansible.builtin.include_vars: ./variables.yml

    - name: "Converge | Include role."
      ansible.builtin.include_role:
        name: spreadcat.newsboat
